# Generated by Django 2.2.5 on 2019-12-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='image',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='userimg', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='mobile',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='手机号'),
        ),
    ]
