# Generated by Django 2.2.5 on 2019-12-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20191209_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='image',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='mobile',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='手机号'),
        ),
    ]
