# Generated by Django 2.2.5 on 2019-12-09 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='goods_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='分类名称')),
                ('created', models.DateField(auto_now=True, null=True, verbose_name='创建时间')),
                ('updated', models.DateField(auto_now_add=True, null=True, verbose_name='修改时间')),
                ('slug', models.CharField(blank=True, max_length=120, null=True, verbose_name='动作')),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Goods.goods_category', verbose_name='自己关联自己')),
            ],
            options={
                'verbose_name': '商品分类表',
                'verbose_name_plural': '商品分类表',
            },
        ),
        migrations.CreateModel(
            name='goods_good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salePrice', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='单价')),
                ('productName', models.CharField(blank=True, max_length=50, null=True, verbose_name='商品名称')),
                ('subTitle', models.CharField(blank=True, max_length=250, null=True, verbose_name='商品标题')),
                ('productImageBig', models.CharField(blank=True, max_length=100, null=True, verbose_name='商品图')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='商品详细')),
                ('created', models.DateField(auto_now=True, null=True, verbose_name='创建时间')),
                ('updated', models.DateField(auto_now_add=True, null=True, verbose_name='修改时间')),
                ('category_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Goods.goods_category', verbose_name='商品分类id')),
            ],
            options={
                'verbose_name': '商品表',
                'verbose_name_plural': '商品表',
            },
        ),
        migrations.CreateModel(
            name='goods_goodimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=100, null=True, verbose_name='商品轮播图')),
                ('created', models.DateField(auto_now=True, null=True, verbose_name='创建时间')),
                ('updated', models.DateField(auto_now_add=True, null=True, verbose_name='修改时间')),
                ('good_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Goods.goods_good', verbose_name='商品id')),
            ],
        ),
    ]
