# Generated by Django 2.2.5 on 2019-12-09 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods_goodimage',
            options={'verbose_name': '商品轮播图片表', 'verbose_name_plural': '商品轮播图片表'},
        ),
    ]
