# Generated by Django 2.2.5 on 2019-12-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0002_auto_20191209_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods_good',
            name='productImageBig',
            field=models.ImageField(blank=True, null=True, upload_to='goodsimg', verbose_name='商品图'),
        ),
    ]
