# Generated by Django 2.2.5 on 2019-12-11 09:04

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0004_auto_20191210_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods_good',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='商品详细'),
        ),
        migrations.AlterField(
            model_name='goods_goodimage',
            name='good_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='Goods.goods_good', verbose_name='商品id'),
        ),
        migrations.AlterField(
            model_name='goods_goodimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='goodschild', verbose_name='商品轮播图'),
        ),
    ]
