# Generated by Django 2.2.5 on 2019-12-09 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='address_address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='姓名')),
                ('tel', models.CharField(blank=True, max_length=11, null=True, verbose_name='联系电话')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='详细地址')),
                ('created', models.DateField(auto_now=True, null=True, verbose_name='创建时间')),
                ('updated', models.DateField(auto_now_add=True, null=True, verbose_name='修改时间')),
                ('is_default', models.BooleanField(blank=True, null=True, verbose_name='默认地址')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户id')),
            ],
            options={
                'verbose_name': '地址表',
                'verbose_name_plural': '地址表',
            },
        ),
    ]
